In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import time

In [ ]:


driver = webdriver.Chrome()
wait = WebDriverWait(driver, 10)

driver.get(
    "https://www.imdb.com/search/title/?title_type=feature&release_date=2024-01-01,2024-12-31&genres=adventure"
)

time.sleep(5)

# ---------- CLICK "50 MORE" UNTIL END ----------
while True:
    try:
        load_more = wait.until(
            EC.element_to_be_clickable(
                (By.CSS_SELECTOR, "button.ipc-see-more__button")
            )
        )

        driver.execute_script(
            "arguments[0].scrollIntoView({block: 'center'});",
            load_more
        )
        time.sleep(1)
        load_more.click()
        time.sleep(3)

    except:
        print("Reached last page ")
        break

# ---------- SCRAPE MOVIES ----------
movies = []
movie_cards = driver.find_elements(
    By.CSS_SELECTOR, "li.ipc-metadata-list-summary-item"
)

print("Total movies loaded:", len(movie_cards))

for card in movie_cards:
    movie = {}

    # TITLE
    try:
        title_text = card.find_element(
            By.CSS_SELECTOR, "h3.ipc-title__text"
        ).text
        movie["title"] = title_text.split(". ", 1)[1]
    except:
        movie["title"] = "N/A"

    # DURATION
    try:
        metadata = card.find_elements(
            By.CSS_SELECTOR, "span.dli-title-metadata-item"
        )
        movie["duration"] = metadata[1].text if len(metadata) > 1 else "N/A"
    except:
        movie["duration"] = "N/A"

    # RATING
    try:
        movie["rating"] = card.find_element(
            By.CSS_SELECTOR, "span.ipc-rating-star--rating"
        ).text
    except:
        movie["rating"] = "N/A"

    #  VOTE COUNT (NEW)
    try:
        votes = card.find_element(
            By.CSS_SELECTOR, "span.ipc-rating-star--voteCount"
        ).text
        movie["vote_count"] = (
            votes.replace("(", "")
                 .replace(")", "")
                 .replace(",", "")
                 .strip()
        )
    except:
        movie["vote_count"] = "N/A"

    # STORYLINE
    try:
        movie["storyline"] = card.find_element(
            By.CSS_SELECTOR, "div.ipc-html-content-inner-div"
        ).text
    except:
        movie["storyline"] = "N/A"

    movies.append(movie)

driver.quit()

df = pd.DataFrame(movies)
print("Total movies scraped:", len(df))
print(df.head())

Reached last page 🎯
Total movies loaded: 660
Total movies scraped: 660
                  title duration rating vote_count  \
0                  Eden    2h 9m    6.5        38K
1        Dune: Part Two   2h 46m    8.4       712K
2          Gladiator II   2h 28m    6.5       287K
3  Deadpool & Wolverine    2h 8m    7.5       551K
4        The Wild Robot   1h 42m    8.2       212K

                                           storyline
0  Based on a factual account of a group of outsi...
1  Paul Atreides unites with the Fremen while on ...
2  After his home is conquered by the tyrannical ...
3  Deadpool is offered a place in the Marvel Cine...
4  After a shipwreck, an intelligent robot called...

In [3]:
df

,title,duration,rating,vote_count,storyline
0,Eden,2h 9m,6.5,38K,Based on a factual account of a group of outsi...
1,Dune: Part Two,2h 46m,8.4,712K,Paul Atreides unites with the Fremen while on ...
2,Gladiator II,2h 28m,6.5,287K,After his home is conquered by the tyrannical ...
3,Deadpool & Wolverine,2h 8m,7.5,551K,Deadpool is offered a place in the Marvel Cine...
4,The Wild Robot,1h 42m,8.2,212K,"After a shipwreck, an intelligent robot called..."
...,...,...,...,...,...
655,One Day the Movie,N/A,N/A,N/A,One Day: The Movie is about two suburban young...
656,I V Y: World of the Future,13+,N/A,N/A,"Now Ivy, Mike, And Claire Must Work Together T..."
657,Labyrint more,1h 1m,N/A,N/A,Do we live in a simulation? The life of show h...
658,Melissa's Birthday,N/A,N/A,N/A,Karen McKarenson plans to bust out of jail to ...
659,Kung Zhu: Amazing Adventures of Zhu,1h 13m,N/A,N/A,N/A

In [4]:
df.to_csv("imdb_adventure_movies_2024.csv", index=False)
print("CSV saved successfully!")

CSV saved successfully!

In [5]:


driver = webdriver.Chrome()
wait = WebDriverWait(driver, 10)

driver.get(
    "https://www.imdb.com/search/title/?title_type=feature&release_date=2024-01-01,2024-12-31&genres=action"
)

time.sleep(5)

# ---------- CLICK "50 MORE" UNTIL END ----------
while True:
    try:
        load_more = wait.until(
            EC.element_to_be_clickable(
                (By.CSS_SELECTOR, "button.ipc-see-more__button")
            )
        )

        driver.execute_script(
            "arguments[0].scrollIntoView({block: 'center'});",
            load_more
        )
        time.sleep(1)
        load_more.click()
        time.sleep(3)

    except:
        print("Reached last page ")
        break

# ---------- SCRAPE MOVIES ----------
movies = []
movie_cards = driver.find_elements(
    By.CSS_SELECTOR, "li.ipc-metadata-list-summary-item"
)

print("Total movies loaded:", len(movie_cards))

for card in movie_cards:
    movie = {}

    # TITLE
    try:
        title_text = card.find_element(
            By.CSS_SELECTOR, "h3.ipc-title__text"
        ).text
        movie["title"] = title_text.split(". ", 1)[1]
    except:
        movie["title"] = "N/A"

    # DURATION
    try:
        metadata = card.find_elements(
            By.CSS_SELECTOR, "span.dli-title-metadata-item"
        )
        movie["duration"] = metadata[1].text if len(metadata) > 1 else "N/A"
    except:
        movie["duration"] = "N/A"

    # RATING
    try:
        movie["rating"] = card.find_element(
            By.CSS_SELECTOR, "span.ipc-rating-star--rating"
        ).text
    except:
        movie["rating"] = "N/A"

    #  VOTE COUNT (NEW)
    try:
        votes = card.find_element(
            By.CSS_SELECTOR, "span.ipc-rating-star--voteCount"
        ).text
        movie["vote_count"] = (
            votes.replace("(", "")
                 .replace(")", "")
                 .replace(",", "")
                 .strip()
        )
    except:
        movie["vote_count"] = "N/A"

    # STORYLINE
    try:
        movie["storyline"] = card.find_element(
            By.CSS_SELECTOR, "div.ipc-html-content-inner-div"
        ).text
    except:
        movie["storyline"] = "N/A"

    movies.append(movie)

driver.quit()

df1 = pd.DataFrame(movies)
print("Total movies scraped:", len(df1))
print(df1.head())

Reached last page
Total movies loaded: 1474
Total movies scraped: 1474
                  title duration rating vote_count  \
0                 Relay   1h 52m    7.0        28K
1        Dune: Part Two   2h 46m    8.4       712K
2             Civil War   1h 49m    7.0       262K
3          Gladiator II   2h 28m    6.5       287K
4  Deadpool & Wolverine    2h 8m    7.5       551K

                                           storyline
0  A broker of lucrative payoffs between corrupt ...
1  Paul Atreides unites with the Fremen while on ...
2  In a dystopian future, four journalists travel...
3  After his home is conquered by the tyrannical ...
4  Deadpool is offered a place in the Marvel Cine...

In [6]:
df1.to_csv("imdb_action_movies_2024.csv", index=False)
print("CSV saved successfully!")

CSV saved successfully!

In [7]:
df1

,title,duration,rating,vote_count,storyline
0,Relay,1h 52m,7.0,28K,A broker of lucrative payoffs between corrupt ...
1,Dune: Part Two,2h 46m,8.4,712K,Paul Atreides unites with the Fremen while on ...
2,Civil War,1h 49m,7.0,262K,"In a dystopian future, four journalists travel..."
3,Gladiator II,2h 28m,6.5,287K,After his home is conquered by the tyrannical ...
4,Deadpool & Wolverine,2h 8m,7.5,551K,Deadpool is offered a place in the Marvel Cine...
...,...,...,...,...,...
1469,Labyrint more,1h 1m,N/A,N/A,Do we live in a simulation? The life of show h...
1470,Full Throttle 2,N/A,N/A,N/A,A professional racing driver speeds into the s...
1471,Angel Vision,2h 3m,N/A,N/A,N/A
1472,Downgraded Citizen,1h 21m,N/A,N/A,A conspiracy unravels as a biological weapon d...
1473,Black and White Rounded,1h 19m,N/A,N/A,N/A

In [8]:
driver = webdriver.Chrome()
wait = WebDriverWait(driver, 10)

driver.get(
    "https://www.imdb.com/search/title/?title_type=feature&release_date=2024-01-01,2024-12-31&genres=animation"
)

time.sleep(5)

# ---------- CLICK "50 MORE" UNTIL END ----------
while True:
    try:
        load_more = wait.until(
            EC.element_to_be_clickable(
                (By.CSS_SELECTOR, "button.ipc-see-more__button")
            )
        )

        driver.execute_script(
            "arguments[0].scrollIntoView({block: 'center'});",
            load_more
        )
        time.sleep(1)
        load_more.click()
        time.sleep(3)

    except:
        print("Reached last page ")
        break

# ---------- SCRAPE MOVIES ----------
movies = []
movie_cards = driver.find_elements(
    By.CSS_SELECTOR, "li.ipc-metadata-list-summary-item"
)

print("Total movies loaded:", len(movie_cards))

for card in movie_cards:
    movie = {}

    # TITLE
    try:
        title_text = card.find_element(
            By.CSS_SELECTOR, "h3.ipc-title__text"
        ).text
        movie["title"] = title_text.split(". ", 1)[1]
    except:
        movie["title"] = "N/A"

    # DURATION
    try:
        metadata = card.find_elements(
            By.CSS_SELECTOR, "span.dli-title-metadata-item"
        )
        movie["duration"] = metadata[1].text if len(metadata) > 1 else "N/A"
    except:
        movie["duration"] = "N/A"

    # RATING
    try:
        movie["rating"] = card.find_element(
            By.CSS_SELECTOR, "span.ipc-rating-star--rating"
        ).text
    except:
        movie["rating"] = "N/A"

    #  VOTE COUNT (NEW)
    try:
        votes = card.find_element(
            By.CSS_SELECTOR, "span.ipc-rating-star--voteCount"
        ).text
        movie["vote_count"] = (
            votes.replace("(", "")
                 .replace(")", "")
                 .replace(",", "")
                 .strip()
        )
    except:
        movie["vote_count"] = "N/A"

    # STORYLINE
    try:
        movie["storyline"] = card.find_element(
            By.CSS_SELECTOR, "div.ipc-html-content-inner-div"
        ).text
    except:
        movie["storyline"] = "N/A"

    movies.append(movie)

driver.quit()

df2 = pd.DataFrame(movies)
print("Total movies scraped:", len(df2))
print(df2.head())

Reached last page
Total movies loaded: 445
Total movies scraped: 445
            title duration rating vote_count  \
0  The Wild Robot   1h 42m    8.2       212K
1            Flow   1h 25m    7.9       121K
2    Inside Out 2   1h 36m    7.5       243K
3         Moana 2   1h 40m    6.3       122K
4              IF   1h 44m    6.4        65K

                                           storyline
0  After a shipwreck, an intelligent robot called...
1  Cat is a solitary animal, but as its home is d...
2  A sequel that features Riley entering puberty ...
3  After receiving an unexpected call from her wa...
4  A young girl who goes through a difficult expe...

In [9]:
df2.to_csv("imdb_animation_movies_2024.csv", index=False)
print("CSV saved successfully!")

CSV saved successfully!

In [10]:
df2

,title,duration,rating,vote_count,storyline
0,The Wild Robot,1h 42m,8.2,212K,"After a shipwreck, an intelligent robot called..."
1,Flow,1h 25m,7.9,121K,"Cat is a solitary animal, but as its home is d..."
2,Inside Out 2,1h 36m,7.5,243K,A sequel that features Riley entering puberty ...
3,Moana 2,1h 40m,6.3,122K,After receiving an unexpected call from her wa...
4,IF,1h 44m,6.4,65K,A young girl who goes through a difficult expe...
...,...,...,...,...,...
440,Hubworld,3h 47m,N/A,N/A,Hubworld is a reflection on the decay of virtu...
441,Abandoned,54m,N/A,N/A,James and Laura step into the deserted watcher...
442,Skullmaster: The Warrior of Havoc,N/A,N/A,N/A,N/A
443,Frost: End of the Ashics,57m,N/A,N/A,The saga continues from Frost: War of the Ashi...
444,People Power,1h 24m,N/A,N/A,Large Metropolis. Near Future. World decimated...

In [11]:
driver = webdriver.Chrome()
wait = WebDriverWait(driver, 10)

driver.get(
    "https://www.imdb.com/search/title/?title_type=feature&release_date=2024-01-01,2024-12-31&genres=crime"
)

time.sleep(5)

# ---------- CLICK "50 MORE" UNTIL END ----------
while True:
    try:
        load_more = wait.until(
            EC.element_to_be_clickable(
                (By.CSS_SELECTOR, "button.ipc-see-more__button")
            )
        )

        driver.execute_script(
            "arguments[0].scrollIntoView({block: 'center'});",
            load_more
        )
        time.sleep(1)
        load_more.click()
        time.sleep(3)

    except:
        print("Reached last page ")
        break

# ---------- SCRAPE MOVIES ----------
movies = []
movie_cards = driver.find_elements(
    By.CSS_SELECTOR, "li.ipc-metadata-list-summary-item"
)

print("Total movies loaded:", len(movie_cards))

for card in movie_cards:
    movie = {}

    # TITLE
    try:
        title_text = card.find_element(
            By.CSS_SELECTOR, "h3.ipc-title__text"
        ).text
        movie["title"] = title_text.split(". ", 1)[1]
    except:
        movie["title"] = "N/A"

    # DURATION
    try:
        metadata = card.find_elements(
            By.CSS_SELECTOR, "span.dli-title-metadata-item"
        )
        movie["duration"] = metadata[1].text if len(metadata) > 1 else "N/A"
    except:
        movie["duration"] = "N/A"

    # RATING
    try:
        movie["rating"] = card.find_element(
            By.CSS_SELECTOR, "span.ipc-rating-star--rating"
        ).text
    except:
        movie["rating"] = "N/A"

    #  VOTE COUNT (NEW)
    try:
        votes = card.find_element(
            By.CSS_SELECTOR, "span.ipc-rating-star--voteCount"
        ).text
        movie["vote_count"] = (
            votes.replace("(", "")
                 .replace(")", "")
                 .replace(",", "")
                 .strip()
        )
    except:
        movie["vote_count"] = "N/A"

    # STORYLINE
    try:
        movie["storyline"] = card.find_element(
            By.CSS_SELECTOR, "div.ipc-html-content-inner-div"
        ).text
    except:
        movie["storyline"] = "N/A"

    movies.append(movie)

driver.quit()

df3 = pd.DataFrame(movies)
print("Total movies scraped:", len(df3))
print(df3.head())

Reached last page
Total movies loaded: 1064
Total movies scraped: 1064
             title duration rating vote_count  \
0          Abigail   1h 49m    6.5       113K
1  The Instigators   1h 41m    6.2        42K
2         Longlegs   1h 41m    6.6       217K
3    The Beekeeper   1h 45m    6.3       175K
4            Wolfs   1h 48m    6.5       100K

                                           storyline
0  After a group of criminals kidnap the ballerin...
1  Follows two robbers who must go on the run wit...
2  In pursuit of a serial killer, an FBI agent un...
3  A former operative of a powerful organization ...
4  Two rival fixers cross paths when they're both...

In [12]:
df3.to_csv("imdb_crime_movies_2024.csv", index=False)
print("CSV saved successfully!")

CSV saved successfully!

In [13]:
df3

,title,duration,rating,vote_count,storyline
0,Abigail,1h 49m,6.5,113K,After a group of criminals kidnap the ballerin...
1,The Instigators,1h 41m,6.2,42K,Follows two robbers who must go on the run wit...
2,Longlegs,1h 41m,6.6,217K,"In pursuit of a serial killer, an FBI agent un..."
3,The Beekeeper,1h 45m,6.3,175K,A former operative of a powerful organization ...
4,Wolfs,1h 48m,6.5,100K,Two rival fixers cross paths when they're both...
...,...,...,...,...,...
1059,Sentence arbitraire,N/A,N/A,N/A,N/A
1060,El Centinela de las Ánimas,1h 17m,N/A,N/A,A tormented undertaker is pursued by horrifyin...
1061,Broken,1h 32m,N/A,N/A,"In a vibrant, futuristic city where technology..."
1062,Tori: Book 1,1h 18m,N/A,N/A,Weg Naar Zee... a beautiful village located at...
1063,Bad Knight in Gotham,2h 35m,N/A,N/A,N/A

In [2]:
driver = webdriver.Chrome()
wait = WebDriverWait(driver, 10)

driver.get(
    "https://www.imdb.com/search/title/?title_type=feature&release_date=2024-01-01,2024-12-31&genres=sci-fi"
)

time.sleep(5)

# ---------- CLICK "50 MORE" UNTIL END ----------
while True:
    try:
        load_more = wait.until(
            EC.element_to_be_clickable(
                (By.CSS_SELECTOR, "button.ipc-see-more__button")
            )
        )

        driver.execute_script(
            "arguments[0].scrollIntoView({block: 'center'});",
            load_more
        )
        time.sleep(1)
        load_more.click()
        time.sleep(3)

    except:
        print("Reached last page ")
        break

# ---------- SCRAPE MOVIES ----------
movies = []
movie_cards = driver.find_elements(
    By.CSS_SELECTOR, "li.ipc-metadata-list-summary-item"
)

print("Total movies loaded:", len(movie_cards))

for card in movie_cards:
    movie = {}

    # TITLE
    try:
        title_text = card.find_element(
            By.CSS_SELECTOR, "h3.ipc-title__text"
        ).text
        movie["title"] = title_text.split(". ", 1)[1]
    except:
        movie["title"] = "N/A"

    # DURATION
    try:
        metadata = card.find_elements(
            By.CSS_SELECTOR, "span.dli-title-metadata-item"
        )
        movie["duration"] = metadata[1].text if len(metadata) > 1 else "N/A"
    except:
        movie["duration"] = "N/A"

    # RATING
    try:
        movie["rating"] = card.find_element(
            By.CSS_SELECTOR, "span.ipc-rating-star--rating"
        ).text
    except:
        movie["rating"] = "N/A"

    #  VOTE COUNT (NEW)
    try:
        votes = card.find_element(
            By.CSS_SELECTOR, "span.ipc-rating-star--voteCount"
        ).text
        movie["vote_count"] = (
            votes.replace("(", "")
                 .replace(")", "")
                 .replace(",", "")
                 .strip()
        )
    except:
        movie["vote_count"] = "N/A"

    # STORYLINE
    try:
        movie["storyline"] = card.find_element(
            By.CSS_SELECTOR, "div.ipc-html-content-inner-div"
        ).text
    except:
        movie["storyline"] = "N/A"

    movies.append(movie)

driver.quit()

df4 = pd.DataFrame(movies)
print("Total movies scraped:", len(df4))
print(df4.head())

Reached last page
Total movies loaded: 662
Total movies scraped: 662
                  title duration rating vote_count  \
0         The Substance   2h 21m    7.2       398K
1     The Life of Chuck   1h 51m    7.3        56K
2        Dune: Part Two   2h 46m    8.4       712K
3  Deadpool & Wolverine    2h 8m    7.5       552K
4        Alien: Romulus   1h 59m    7.1       280K

                                           storyline
0  A fading celebrity takes a black-market drug: ...
1  A life-affirming, genre-bending story about th...
2  Paul Atreides unites with the Fremen while on ...
3  Deadpool is offered a place in the Marvel Cine...
4  While scavenging the deep ends of a derelict s...

In [3]:
df4.to_csv("imdb_sci-fi_movies_2024.csv", index=False)
print("CSV saved successfully!")

CSV saved successfully!

In [4]:
df4

,title,duration,rating,vote_count,storyline
0,The Substance,2h 21m,7.2,398K,A fading celebrity takes a black-market drug: ...
1,The Life of Chuck,1h 51m,7.3,56K,"A life-affirming, genre-bending story about th..."
2,Dune: Part Two,2h 46m,8.4,712K,Paul Atreides unites with the Fremen while on ...
3,Deadpool & Wolverine,2h 8m,7.5,552K,Deadpool is offered a place in the Marvel Cine...
4,Alien: Romulus,1h 59m,7.1,280K,While scavenging the deep ends of a derelict s...
...,...,...,...,...,...
657,Macproud,N/A,N/A,N/A,A man and his soul are connected between reali...
658,Planet Magnon,1h 32m,N/A,N/A,N/A
659,Labyrint more,1h 1m,N/A,N/A,Do we live in a simulation? The life of show h...
660,Miss Roboto,N/A,N/A,N/A,N/A
661,5 More Minutes,N/A,N/A,N/A,Eli Lees struggles with balancing his school a...

In [5]:
import pandas as pd
import glob

csv_files = glob.glob("*.csv")  

df = pd.concat(
    (pd.read_csv(file) for file in csv_files),
    ignore_index=True
)

df.to_csv("imdb_movies.csv", index=False)

In [6]:
df

,title,duration,rating,vote_count,storyline
0,Relay,1h 52m,7.0,28K,A broker of lucrative payoffs between corrupt ...
1,Dune: Part Two,2h 46m,8.4,712K,Paul Atreides unites with the Fremen while on ...
2,Civil War,1h 49m,7.0,262K,"In a dystopian future, four journalists travel..."
3,Gladiator II,2h 28m,6.5,287K,After his home is conquered by the tyrannical ...
4,Deadpool & Wolverine,2h 8m,7.5,551K,Deadpool is offered a place in the Marvel Cine...
...,...,...,...,...,...
4300,Macproud,NaN,NaN,NaN,A man and his soul are connected between reali...
4301,Planet Magnon,1h 32m,NaN,NaN,NaN
4302,Labyrint more,1h 1m,NaN,NaN,Do we live in a simulation? The life of show h...
4303,Miss Roboto,NaN,NaN,NaN,NaN
4304,5 More Minutes,NaN,NaN,NaN,Eli Lees struggles with balancing his school a...